using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Decider
{
    class Program
    {
        static void Main(string[] args)
        {
            Lexer lex = new Lexer();
            Parser p = new Parser(); 
            Console.Write("Is this expression generated by the grammar: ");
            string exp = Console.ReadLine(); 
            List<Token> input = lex.Tokenize(exp);
            p.Parse(input); 
        }
    }
}
